name: Generate Pac-Man Contribution Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

# Explicitly define job permissions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          # github user name to read the contribution graph from
          github_user_name: ${{ github.repository_owner }}
          
          # Use Pac-Man themed outputs with custom colors
          outputs: |
            dist/github-contribution-pacman.svg?color_snake=ffcc00&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/github-contribution-pacman-dark.svg?color_snake=ffcc00&color_dots=#161b22,#0d1117,#0e4429,#006d32,#26a641&palette=github-dark
            dist/github-contribution-pacman-anim.gif?color_snake=ffcc00&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      # Debug step to see current directory content  
      - name: List output files
        run: ls -la dist/
            
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}